server:
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/city_quest?useSSL=false
    username: root
    password: 12345
    pool-size: 100
  jpa:
    driver: com.mysql.cj.jdbc.Driver
    hibernate:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
      ddl-auto: update

bot:
  name: bot_name
  token: bot_token